# .github/workflows/deno-ci.yml  ← [신규 추가]
name: deno-ci
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with: { deno-version: v1.x }
      - run: deno fmt --check
      - run: deno lint
      - run: deno check main.ts
